spring:
  application:
    name: parking-system

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parking_system?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.qsx.parking

knife4j:
  enable: true
  setting:
    language: zh_cn

jwt:
  token:
    tokenExpiration: 120  # 有效时间,分钟
    tokenSignKey: parking-system  # 签名秘钥

# 服务端口配置
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

parking:  # 停车场配置
  exitTimeOut: 1  # 离场超时时间，单位分钟

