version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: parking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking_system
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - parking-network

  app:
    build: .
    container_name: parking-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/parking_system
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - parking-network

volumes:
  mysql-data:

networks:
  parking-network:
    driver: bridge 